version: '3'
services:
  loadbalancer:
    image: snap-web-loadbalancer-dev
    build:
      context: ./loadbalancer
      dockerfile: Dockerfile.dev
      args:
        - BUILD_DATE
        - COMMIT
    environment:
      - NGINX_HOST=marcs.local
    depends_on:
      - webpack-hot
  api:
    image: snap-web-api-dev
    build:
      context: ./api/
      args:
        - BUILD_DATE
        - COMMIT
    environment:
      - LOG_LEVEL=info
  webpack-hot:
    image: snap-web-webpack-hot
    build:
      context: ./loadbalancer/react-frontend
      dockerfile: Dockerfile.dev
      args:
        - BUILD_DATE
        - COMMIT
    expose:
      - 8080
    volumes:
      - ./loadbalancer/react-frontend/src:/bindmount/src
