# ------- Pre-compiling ---------------------------------
# -- main build ----

FROM nginxinc/nginx-unprivileged:1.21.1-alpine

COPY http.conf /etc/nginx/conf.d/http.conf
COPY masked_logging.conf /etc/nginx/conf.d/masked_logging.conf
COPY mask_ip_address.js /etc/nginx/conf.d/mask_ip_address.js
COPY location_api.conf /etc/nginx/conf.d/location_api.conf
COPY nginx.conf.dev.template /etc/nginx/conf.d/nginx.conf.template


# Need root to make proxy_cache directory
USER root
RUN mkdir -p /cache/proxy \
    && chown -R 101:0 /cache/proxy \
    && chmod -R g+w /cache/proxy


# And the temp directories

ARG MARCS_DATA_FILE
RUN mkdir /tmp/marcsimport
COPY $MARCS_DATA_FILE /tmp/marcsimport/marcs-data-file.tar.gz
#COPY --from=snap /downloads/. /usr/share/nginx/html/downloads
RUN tar -xvf /tmp/marcsimport/marcs-data-file.tar.gz -C /tmp/marcsimport \
    && mv /tmp/marcsimport/output/web/downloads /usr/share/nginx/html/downloads \
    && chown -R 101:0 /usr/share/nginx/html/downloads \
    && chmod -R g-wx /usr/share/nginx/html/downloads \
    && rm -rf /tmp/marcsimport

USER 101

COPY ./static/ /usr/share/nginx/html/static

ENV NGINX_HOST localhost

LABEL org.label-schema.vcs-ref="$COMMIT" \
      org.label-schema.build-date="$BUILD_DATE"

CMD envsubst '$NGINX_HOST' < /etc/nginx/conf.d/nginx.conf.template > /tmp/nginx.conf && exec nginx -c /tmp/nginx.conf -g 'daemon off;'