## This is the dockerfile for "hot" loading of webpack
FROM node:16-bullseye

EXPOSE 8080
WORKDIR /bindmount

COPY package-lock.json package.json ./
RUN npm install --no-progress --ignore-optional --legacy-peer-deps

COPY webpack.config.js ./
COPY data ./data

ARG MARCS_DATA_FILE
RUN mkdir /tmp/marcsimport
COPY $MARCS_DATA_FILE /tmp/marcsimport/marcs-data-file.tar.gz
RUN tar -xvf /tmp/marcsimport/marcs-data-file.tar.gz -C /tmp/marcsimport \
    && mv /tmp/marcsimport/output/web/precompiled/* ./data/ \
    && rm -rf /tmp/marcsimport

COPY config ./config

# Matomo tracking:
ARG MATOMO_URL_BASE="http://localhost"
ARG MATOMO_SITE_ID=1
ARG MATOMO_DISABLED="true"
ARG MATOMO_DEBUG="true"

RUN echo "export const MATOMO_URL_BASE = '$MATOMO_URL_BASE';\nexport const MATOMO_SITE_ID = $MATOMO_SITE_ID;\nexport const MATOMO_DISABLED = '$MATOMO_DISABLED';\nexport const MATOMO_DEBUG = '$MATOMO_DEBUG';" > ./data/matomo.js

ARG BUILD_DATE
ARG COMMIT
ARG BUILD_TYPE='dev'

LABEL org.label-schema.vcs-ref="$COMMIT" \
      org.label-schema.build-date="$BUILD_DATE"

RUN echo "export const WEB_INTERFACE_BUILD_DATE = '$BUILD_DATE';\nexport const WEB_INTERFACE_BUILD_COMMIT = '$COMMIT';\nexport const WEB_INTERFACE_BUILD_TYPE = '$BUILD_TYPE';" > ./data/build.js

CMD npm run start